services:
  - type: web
    name: ticketsystem-backend
    runtime: python
    plan: free
    buildCommand: "bash build.sh"
    startCommand: "gunicorn ticketsystemproject.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.7
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: "ticketsystem-backend.onrender.com"
      - key: CORS_ALLOWED_ORIGINS
        value: "https://your-frontend.vercel.app"
      - key: DATABASE_URL
        fromDatabase:
          name: ticketsystem-db
          property: connectionString

databases:
  - name: ticketsystem-db
    plan: free
