services:
  - type: web
    name: ticketsystem-backend
    runtime: python
    plan: free
    buildCommand: "bash build.sh"
    startCommand: "gunicorn ticketsystemproject.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.7
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: "ticketsystem-backend.onrender.com"
      - key: CORS_ALLOWED_ORIGINS
        value: "https://is-project-zqko.vercel.app"
      - key: DATABASE_URL
        value: "postgresql://neondb_owner:npg_trdz6BZOVv9k@ep-silent-feather-aipr07h3-pooler.c-4.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require"
      - key: DJANGO_SUPERUSER_USERNAME
        value: "THUREYA"
      - key: DJANGO_SUPERUSER_EMAIL
        value: "thureya@example.com"
      - key: DJANGO_SUPERUSER_PASSWORD
        value: "Thureya@2004"

databases:
  - name: ticketsystem-db
    plan: free
